name: Auto Commit

#on:
#  schedule:
#    - cron: "*/5 * * * *"

on:
  push

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Edit the data.txt file
        run: |
          git clone https://Leikt:{secret.TOKEN}@github.com/Leikt/autoopensource.git
          cd autoopensource
          
          date >> data.txt
          
          git config --global user.email "leikt.solreihin@gmail.com"
          git config --global user.name "Leikt"
          
          git add data.txt
          git commit -m "feat: today"
          git push