name: Auto Commit

on:
  schedule:
    - cron: "0 */8 * * *"
#  push:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: "${{secrets.GITHUB_TOKEN}}"

      - run: |
          python generate.py

      - run: |
          current_date=$(date +%Y/%m/%d-%H:%M:%S)
          git config user.email "leikt.solreihin@gmail.com"
          git config user.name "Leikt"
          git add .
          git commit -m "autocommit ${current_date}"
          git push
