name: Auto Commit

on:
  schedule:
    - cron: "*/15 * * * *"

#on:
#  push

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: "${{secrets.TOKEN}}"

      - run: |
          date > date.txt

      - run: |
          current_date=$(date +%Y/%m/%d-%H:%M:%S)
          git config user.email "leikt.solreihin@gmail.com"
          git config user.name "Leikt"
          git add date.txt
          git commit -m "autocommit ${current_date}"
          git push